/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated.budgets'
import { Route as AuthenticatedGuardrailsRouteImport } from './routes/_authenticated.guardrails'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated.keys'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated.logs'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated.models'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated.organization'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated.overview'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated.providers'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated.teams'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated.usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardrailsRoute = AuthenticatedGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/guardrails': typeof AuthenticatedGuardrailsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/usage': typeof AuthenticatedUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/guardrails': typeof AuthenticatedGuardrailsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/usage': typeof AuthenticatedUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/guardrails': typeof AuthenticatedGuardrailsRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/budgets'
    | '/guardrails'
    | '/keys'
    | '/logs'
    | '/models'
    | '/organization'
    | '/overview'
    | '/providers'
    | '/teams'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/budgets'
    | '/guardrails'
    | '/keys'
    | '/logs'
    | '/models'
    | '/organization'
    | '/overview'
    | '/providers'
    | '/teams'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/budgets'
    | '/_authenticated/guardrails'
    | '/_authenticated/keys'
    | '/_authenticated/logs'
    | '/_authenticated/models'
    | '/_authenticated/organization'
    | '/_authenticated/overview'
    | '/_authenticated/providers'
    | '/_authenticated/teams'
    | '/_authenticated/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardrails': {
      id: '/_authenticated/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof AuthenticatedGuardrailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedGuardrailsRoute: typeof AuthenticatedGuardrailsRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedGuardrailsRoute: AuthenticatedGuardrailsRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
